name: SANDBOX

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: ${{ secrets.SECRET_NAME }}
    env:
      PUBLIC_NAME: ${{ env.PUBLIC_NAME }}

    steps:
      - name: DEBUG
        run: echo $NAME
      - name: DEBUG2
        run: echo $PUBLIC_NAME
