name: SANDBOX

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: Gurkenhut

    steps:
      - name: DEBUG
        run: echo $NAME
